# flake8: noqa: F403, F405
# pylint: disable=undefined-variable
import convert_case

from src.bedrock.game_context import *


def get_all_game_events() -> list[str]:
    # unverified_lst = [
    #     "AdditionalContentLoaded",
    #     "AgentCommand",
    #     "AgentCreated",
    #     "ApiInit",
    #     "AppPaused",
    #     "AppResumed",
    #     "AppSuspended",
    #     "AwardAchievement",
    #     "BlockBroken",
    #     "BlockPlaced",
    #     "BoardTextUpdated",
    #     "BookEdited",
    #     "BookExported",
    #     "BookImageImported",
    #     "BossKilled",
    #     "CameraUsed",
    #     "CauldronUsed",
    #     "ConfigurationChanged",
    #     "ConnectionFailed",
    #     "CraftingSessionCompleted",
    #     "CraftingSessionEnd",
    #     "CraftingSessionStart",
    #     "EndOfDay",
    #     "EntitySpawned",
    #     "FileTransmissionCancelled",
    #     "FileTransmissionCompleted",
    #     "FileTransmissionStarted",
    #     "FirstTimeClientOpen",
    #     "FocusGained",
    #     "FocusLost",
    #     "GameplayTipShown",
    #     "GameRulesLoaded",
    #     "GameRulesUpdated",
    #     "GameSessionComplete",
    #     "GameSessionStart",
    #     "GameTypeChanged",
    #     "GrindstoneBlockUsed",
    #     "HardwareInfo",
    #     "HasNewContent",
    #     "ItemAcquired",
    #     "ItemCrafted",
    #     "ItemDestroyed",
    #     "ItemDropped",
    #     "ItemEnchanted",
    #     "ItemEquipped",
    #     "ItemInteracted",
    #     "ItemNamed",
    #     "ItemSmelted",
    #     "ItemUsed",
    #     "JoinCanceled",
    #     "JukeboxUsed",
    #     "LicenseCensus",
    #     "MascotCreated",
    #     "MenuShown",
    #     "MobInteracted",
    #     "MobKilled",
    #     "MultiplayerConnectionStateChanged",
    #     "MultiplayerRoundEnd",
    #     "MultiplayerRoundStart",
    #     "NpcPropertiesUpdated",
    #     "OptionsUpdated",
    #     "performanceMetrics",
    #     "PackImportStage",
    #     "PlayerBounced",
    #     "PlayerDied",
    #     "PlayerJoin",
    #     "PlayerLeave",
    #     "PlayerMessage",
    #     "PlayerTeleported",
    #     # "PlayerTransform",
    #     # "PlayerTravelled",
    #     "PlayerSaved",
    #     "PortalBuilt",
    #     "PortalUsed",
    #     "PortfolioExported",
    #     "PotionBrewed",
    #     "PurchaseAttempt",
    #     "PurchaseResolved",
    #     "RegionalPopup",
    #     "RespondedToAcceptContent",
    #     "ScreenChanged",
    #     "ScreenHeartbeat",
    #     "SignInToEdu",
    #     "SignInToXboxLive",
    #     "SignOutOfXboxLive",
    #     "SpecialMobBuilt",
    #     "StartClient",
    #     "StartWorld",
    #     "TextToSpeechToggled",
    #     "UgcDownloadCompleted",
    #     "UgcDownloadStarted",
    #     "UploadSkin",
    #     "VehicleExited",
    #     "WorldExported",
    #     "WorldFilesListed",
    #     "WorldGenerated",
    #     "WorldLoaded",
    #     "WorldUnloaded",
    #     "SignedBookOpened",
    #     "CommandBlockEdited",
    #     "MobBorn",
    #     "PetDied",
    #     "FishBucketed",
    #     "BellBlockUsed",
    #     "PatternRemoved",
    #     "EntityInteracted",
    #     "CauldronBlockUsed",
    #     "ComposterBlockUsed",
    #     "SlashCommandExecuted",
    #     "Respawn",
    #     "Storage",
    #     "Heartbeat",
    #     "ScriptRan",
    #     "SignInEdu",
    #     "BlockFound",
    #     "BookCopied",
    #     "JoinByCode",
    #     "OfferRated",
    #     "PackPlayed",
    #     "AppUnpaused",
    #     "DwellerDied",
    #     "RealmShared",
    #     "SkinChanged",
    #     "StackLoaded",
    #     "StoreSearch",
    #     "VideoPlayed",
    #     "AssertFailed",
    #     "EntityDanced",
    #     "LicenseCheck",
    #     # "POIBlockUsed",
    #     "PatternAdded",
    #     "ScriptLoaded",
    #     "ContentShared",
    #     "DifficultySet",
    #     "LevelDestruct",
    #     "PopupFiredEdu",
    #     "StorageReport",
    #     "TreatmentsSet",
    #     "WorldImported",
    #     "BehaviorFailed",
    #     "CaravanChanged",
    #     "DevConsoleOpen",
    #     "TradeCompleted",
    #     "ArmorStandPosed",
    #     "BarrelBlockUsed",
    #     "BehaviorErrored",
    #     "ClientIdCreated",
    #     "LabTableCreated",
    #     "PackHashChanged",
    #     "PlayerMessageMe",
    #     "IncognitoFailure",
    #     "LecternBlockUsed",
    #     "MobEffectChanged",
    #     "PlayerMessageSay",
    #     "CampfireBlockUsed",
    #     "DevConsoleCommand",
    #     "FloatPropertyList",
    #     "PackImportStarted",
    #     "PlayerMessageChat",
    #     "PlayerMessageTell",
    #     "RealmUrlGenerated",
    #     "StoreOfferClicked",
    #     "TreatmentsCleared",
    #     "LevelDatLoadFailed",
    #     "PackUpgradeAttempt",
    #     "PerformanceMetrics",
    #     "PlayerMessageTitle",
    #     "SearchItemSelected",
    #     "SplitScreenUpdated",
    #     "StructureGenerated",
    #     "EntitlementListInfo",
    #     "NewUserPackDetected",
    #     "PurchaseGameAttempt",
    #     "ReducerBlockEntered",
    #     "BlockPlacedByCommand",
    #     "CartographyBlockUsed",
    #     "ExperimentalGameplay",
    #     # "POIBlockUsageAttempt",
    #     "SearchCatalogRequest",
    #     "TreatmentPackApplied",
    #     "TreatmentPackRemoved",
    #     "UnknownBlockReceived",
    #     "FileTransmissionState",
    #     "HowToPlayTopicChanged",
    #     "PackImportedCompleted",
    #     "ArmorStandItemEquipped",
    #     "CompoundCreatorCreated",
    #     "DefaultGameTypeChanged",
    #     "ElementConstructorUsed",
    #     "PurchaseFailureDetails",
    #     "PushNotificationOpened",
    #     "RealmMemberlistCleared",
    #     "AppConfigurationChanged",
    #     "SetValidForAchievements",
    #     "TreatmentPackDownloaded",
    #     "MultiplayerSessionUpdate",
    #     "PushNotificationReceived",
    #     "TrialDeviceIdCorrelation",
    #     "ContentLogsInWorldSession",
    #     "StoreOfferPurchaseAttempt",
    #     "StoreOfferPurchaseFailure",
    #     "PushNotificationPermission",
    #     "StoreOfferPurchaseResolved",
    #     "StorePromotionNotification",
    #     "SetMultiplayerCorrelationId",
    #     "PromotionNotificationClicked",
    #     "NewStoreContentCheckCompleted",
    #     "WorldHistoryPackSourceMissingDuringUpgrade",
    #     "FixedMarketplaceWorldUsingV2VillagersToUseV1",
    #     "EduOptionSet",
    #     "EduResources",
    #     "StructureExport",
    #     "CodeBuilderClosed",
    #     "ChatSettingsUpdated",
    #     "CodeBuilderDownload",
    #     "ControlRemappedByPlayer",
    #     # "EduiOSPurchaseTransaction",
    # ]

    lst = [
        'BlockBroken',
        'BlockPlaced',
        'ChunkChanged',
        'ChunkLoaded',
        'ChunkUnloaded',
        'EndOfDay',
        'EntityInteracted',
        'EntitySpawned',
        'ItemAcquired',
        'ItemCrafted',
        'ItemDropped',
        'ItemEquipped',
        'ItemInteracted',
        'ItemUsed',
        'MobInteracted',
        'MobKilled',
        'PlayerBounced',
        'PlayerDied',
        'PlayerJoin',
        'PlayerLeave',
        'PlayerMessage',
        'PlayerTeleported',
        'PlayerTransform',
        'PlayerTravelled',
    ]
    lst = [convert_case.pascal_case(event) for event in lst]
    return lst


def get_game_context(name: str) -> type[GameContext]:
    # return the context class based on the event name
    name = convert_case.pascal_case(name)
    return {
        'BlockBroken': BlockBrokenContext,
        'BlockPlaced': BlockPlacedContext,
        'ChunkChanged': ChunkChangedContext,
        'ChunkLoaded': ChunkLoadedContext,
        'ChunkUnloaded': ChunkUnloadedContext,
        'EndOfDay': EndOfDayContext,
        'EntityInteracted': EntityInteractedContext,
        'EntitySpawned': EntitySpawnedContext,
        'ItemAcquired': ItemAcquiredContext,
        'ItemCrafted': ItemCraftedContext,
        'ItemDropped': ItemDroppedContext,
        'ItemEquipped': ItemEquippedContext,
        'ItemInteracted': ItemInteractedContext,
        'ItemUsed': ItemUsedContext,
        'MobInteracted': MobInteractedContext,
        'MobKilled': MobKilledContext,
        'PlayerBounced': PlayerBouncedContext,
        'PlayerDied': PlayerDiedContext,
        'PlayerJoin': PlayerJoinContext,
        'PlayerLeave': PlayerLeaveContext,
        'PlayerMessage': PlayerMessageContext,
        'PlayerTeleported': PlayerTeleportedContext,
        'PlayerTransform': PlayerTransformContext,
        'PlayerTravelled': PlayerTravelledContext,
    }[name]
